### ISSUE TITLE
Feature search author

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#1]
# To List books of a particular author
The program should take the users input for the author and display the books written by the author and its ratings.

## Resources
https://www.datacamp.com/community/blog/python-pandas-cheat-sheet
<hr>
** Bounty points alloted : 70 **
Any further improvements along with bug fixes will be given brownie points. 
If the contributor sees any further improvements that can be done to this project, raise an issue.

**Comment by keju27** [comment]
Can I work on this issue? Thanks

**Comment by adarshnair094** [comment]
Hey! I would like to work on this issue. Thanks!

**Comment by sudeep-daivajna** [comment]
Hey! would love to work on this issue.. Thanks!

**Comment by menon123** [comment]
hey! I would like to work in this issue. Thanks

**Comment by Smuzzy-waiii** [comment]
May I work on this issue

**Comment by Skanda-Prasad** [comment]
May I work on this issue?

**Comment by Smuzzy-waiii** [comment]
Hii, I have created PR for this, Pls review :)
