### ISSUE TITLE
Enchancement rating range

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#2]
# Rating Range
## generate books within a certain rating range
Currently, the book generates random books whose ratings are above a certain value given as input by the user. An enhancement would be to generate books within a certain range of rating, the upper limit and the lower limit given as the input by the user.

## Understanding code
Takes the rating input from user, converts it to floating-point number, compares it with the rating column on the csv file and displays a random book with a rating higher than that.
<hr>
** Bounty points alloted : 40**
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by menon123** [comment]
hey! I would like to work in this issue. Thanks

**Comment by keju27** [comment]
Hey! I would like to work on this issue. Thanks!

**Comment by Smuzzy-waiii** [comment]
Can I be assigned to this

**Comment by prishagoel** [comment]
Hi, I would like to work on this
