### ISSUE TITLE
Enhancement visualization

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#4]
# Visualization
##Visualization of authors proportion
Visualization of the top 5 authors with the highest average ratings on their books in the form of charts or graphs. 
Can use pandas, mathlib, etc
<hr>
** Bounty points alloted : 120 **
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by anirudhlakhotia** [comment]
I wish to be assigned to this

**Comment by RakshithRAcharya** [comment]
I have created a PR for this please check........tell me If I have to add something more

**Comment by keju27** [comment]
Hey! can I work on this?

**Comment by AyushmaanKaushik** [comment]
Done
