### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#43]
# to fx the buggy code
# description
the code breaks at multiple points, each code fix warrants 15 points!

**Comment by naveen-jacob** [comment]
hi can i work on this?

**Comment by anirudhlakhotia** [comment]
I'd like to work on this

**Comment by ishitabinz** [comment]
Hi, may I work on this issue?

**Comment by JoyenBenitto** [comment]
hi can I work on this

**Comment by keju27** [comment]
hey! Can I work on this issue. Thanks!

**Comment by JoyenBenitto** [comment]
I have submitted the pr after removing 2 bugs can someone verify it
