### ISSUE TITLE
Bug- syntax error

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#6]
# Syntax Error
# Description
A basic python syntax error which is breaking the code.
<hr>
** Bounty points alloted : 20 ** 
Any further improvements along with bug fixes will be given brownie points. If the countributor sees any further inprovements that can be done to this project ,raise an issue.

**Comment by PavvanPradeep** [comment]
can i work on this issue please

**Comment by siddarthpai** [comment]
could i please work on this issue

**Comment by Mana120** [comment]
can i please work on this issue

**Comment by karunakc** [comment]
The issue has been closed now, thank you for asking to be assigned to it!
