### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/Book-Recommendation-System#7]
# Documentation
# Description
To create a proper README.md for the project such that it can be easily understood by anybody going over the repository for the first time.
# Frame
- project title
- project description
- tools used (languages and framework)
- how to clone it into your system (with commands and proper step by step instructions)
- steps to run the file on your system (with commands and proper step by step instructions)
- necessary installations to run the code (link an installation guide)

<hr>
** Bounty points alloted : 45 ** 

Any further improvements along with bug fixes will be given brownie points. If the countributor sees any further inprovements that can be done to this project ,raise an issue.

**Comment by karunakc** [comment]
> Can I get assigned to this issue?

Sure, all the best!

**Comment by Noel-Saju** [comment]
To all documentation contributors~ make sure you make meaningful contributions to the documentation that are actually helpful. PR's including single line changes etc will not be encouraged or accepted. Do keep this in mind while you submit a pull request.
